apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: iam-thesis
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
